#!/usr/bin/env bash
# this is the startup script to start testindicator
if [ $# == 0 ]; then
	title="Directory to watch?"
	inputbox="Please enter the directory to watch for changes"
	watch_dir=$(gdialog --title "$title" --inputbox "$inputbox" 200 100 2>&1)
	if [ $? != 0 ]; then
		exit 2
	fi
else
	watch_dir=$1
fi
/usr/bin/python /usr/share/testindicator/ "$watch_dir"
